### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by bsakweson** [vinta/vinta.ws#7]
Hello Vinta,

So I like your approach and I am hoping this my help me solve my HA implementation of Wordpress. I followed your blog and created a helm chart that I plan to publish but I cannot get it to startup and there are some details I am missing about the images you used. One example would be the image you used in the cron job, is that the same images as the one used in the deployment?

**Comment by vinta** [comment]
@bsakweson Yes, the image I used in CronJob is the same as the one used in Deployment. See https://github.com/vinta/vinta.ws/blob/master/kubernetes/wordpress/04-cronjob.yml
